version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: on-failure
    environment:
      NODE_ENV: development
    ports:
      - 3333:3000
    volumes:
      - ./:/var/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
